import type {
  AchievementEntry,
  ExperienceEntry,
  InterestEntry,
  ResearchArea,
  SiteProfile,
  SkillGroup,
  WorkEntry,
} from "./types";

const updatedAt = "2026-07-26";

export const siteProfiles: SiteProfile[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    name: "齐梓桐",
    alternateName: "Zitong Qi",
    field: "计算机视觉与多模态学习",
    eyebrow: "宁波大学 · 数学与应用数学本科生",
    introduction:
      "我关注视频理解、视觉语言模型与多模态表征学习，尝试把研究方法转化为可复现、可部署的 AI 系统。目前持续开展智能视频分析与医学影像多模态对齐相关工作。",
    availability: "开放计算机视觉与多模态方向的科研交流和实习机会。",
    current: "宁波大学 · 数学与应用数学",
    location: "中国 · 宁波",
    github: "https://github.com/fingercd",
    focus: ["视频理解与异常检测", "视觉语言模型", "可靠评测与系统落地"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    name: "Zitong Qi",
    alternateName: "齐梓桐",
    field: "Computer Vision & Multimodal Learning",
    eyebrow: "Mathematics undergraduate at Ningbo University",
    introduction:
      "I work on video understanding, vision-language models, and multimodal representation learning. My goal is to turn research ideas into reproducible, deployable AI systems, with current work spanning intelligent video analytics and multimodal medical imaging.",
    availability:
      "Open to research conversations and internship opportunities in computer vision and multimodal AI.",
    current: "Ningbo University · Mathematics",
    location: "Ningbo, China",
    github: "https://github.com/fingercd",
    focus: [
      "Video understanding",
      "Vision-language models",
      "Reliable evaluation & deployment",
    ],
  },
];

export const researchAreas: ResearchArea[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "video-understanding",
    order: 1,
    title: "视频理解与异常检测",
    question: "如何让系统理解长视频中的关键事件，而不只是逐帧识别目标？",
    description:
      "研究弱监督异常定位、长时序表征与开放集判别，让模型从连续视频中发现、定位并解释值得关注的事件。",
    methods: ["VideoMAE", "CLIP", "Weakly-supervised MIL", "Temporal modeling"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "multimodal-alignment",
    order: 2,
    title: "视觉语言模型与多模态对齐",
    question: "如何在有限算力下，把视觉、语言与结构化信息对齐到可用表征？",
    description:
      "关注参数高效微调、跨模态对比学习与结构化提示，将通用视觉语言模型适配到安防和医学影像等专业场景。",
    methods: ["Qwen-VL", "LoRA / QLoRA", "SigLIP-style alignment", "Transformers"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "reliable-ai",
    order: 3,
    title: "可靠评测与可部署 AI",
    question: "如何证明模型真的学到了目标能力，并把它稳定接入实际系统？",
    description:
      "从数据泄漏、消融评测和失败样例出发建立可信证据，再用模块化服务和可观测流程打通训练、评测与应用。",
    methods: ["Evaluation protocols", "Ablation studies", "PyTorch", "Web systems"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "video-understanding",
    order: 1,
    title: "Video Understanding & Anomaly Detection",
    question:
      "How can a system understand important events in long videos instead of treating frames in isolation?",
    description:
      "I explore weakly supervised localization, long-range video representations, and open-set reasoning so models can detect, localize, and explain noteworthy events.",
    methods: ["VideoMAE", "CLIP", "Weakly-supervised MIL", "Temporal modeling"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "multimodal-alignment",
    order: 2,
    title: "Vision-Language Models & Alignment",
    question:
      "How can visual, textual, and structured signals be aligned under practical compute constraints?",
    description:
      "My work uses parameter-efficient adaptation, contrastive learning, and structured prompting to bring general vision-language models into security and medical-imaging settings.",
    methods: ["Qwen-VL", "LoRA / QLoRA", "SigLIP-style alignment", "Transformers"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "reliable-ai",
    order: 3,
    title: "Reliable Evaluation & Deployable AI",
    question:
      "How do we verify that a model learned the intended capability and integrate it into a dependable system?",
    description:
      "I use leakage-aware protocols, ablations, and failure analysis to establish evidence, then connect training and evaluation to modular, observable applications.",
    methods: ["Evaluation protocols", "Ablation studies", "PyTorch", "Web systems"],
  },
];

export const projects: WorkEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    slug: "safecommunity-ai",
    order: 1,
    kind: "工程项目",
    title: "SafeCommunity AI",
    year: "2026",
    status: "公开代码",
    summary:
      "面向复杂监控场景的多通道智能视频分析系统，覆盖目标跟踪、规则告警、异常识别与视觉语言模型复核。",
    challenge:
      "传统安防系统依赖固定规则，容易误报，也难以说明事件为什么异常。项目需要同时处理长时序视频、开放集事件和可读的语言解释。",
    role: "核心算法与系统工程",
    contributions: [
      "组合 VideoMAE 与 CLIP 表征，并使用 Attention Pooling 和 Top-K MIL 聚合关键片段。",
      "以 QLoRA 适配视觉语言模型，配合结构化提示完成事件复核与解释。",
      "构建多路视频、ROI 规则、跟踪与告警闭环的 Web 展示系统。",
    ],
    result:
      "完成“感知—判别—解释”的端到端闭环，并在公开视频异常数据上完成系统评测；公开仓库提供架构与实现证据。",
    methods: [
      "PyTorch",
      "VideoMAE",
      "CLIP",
      "Qwen-VL",
      "QLoRA",
      "Flask",
      "ByteTrack",
    ],
    image: {
      src: "/images/safecommunity.svg",
      alt: "SafeCommunity AI 从视频感知、异常判别到语言解释的系统架构图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/SafeCommunity-AI",
        kind: "github",
      },
    ],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-multimodal-alignment",
    slug: "medical-multimodal-alignment",
    order: 2,
    kind: "科研项目",
    title: "脑影像多模态临床预测",
    year: "2026",
    status: "Research in Progress",
    summary:
      "在冻结 3D MRI 编码器的基础上，对齐脑影像、区域体积与临床文本表征，探索轻量多模态增强。",
    challenge:
      "预训练 MRI 编码器能够提取影像表征，却不直接包含脑区体积和临床语义。直接重训成本高，评测中还需避免认知评分等信息造成标签泄漏。",
    role: "多模态方法设计、实验与评测",
    contributions: [
      "设计 SigLIP 风格跨模态对比目标，将影像、结构化体积与临床文本映射到共享空间。",
      "采用冻结编码器与轻量投影层，控制训练成本并保留可迁移性。",
      "设计排除认知捷径的评测协议，并开展跨模态消融与失败分析。",
    ],
    result:
      "研究仍在进行中。为保护未发表工作，本页仅公开问题定义、方法框架和评测原则，不展示投稿信息、内部指标或受控数据。",
    methods: [
      "3D MRI",
      "Contrastive learning",
      "BioClinicalBERT",
      "Leakage-aware evaluation",
      "PyTorch",
    ],
    image: {
      src: "/images/medical-alignment.svg",
      alt: "医学影像、脑区体积和临床信息对齐到共享表征空间的框架图",
    },
    links: [],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "dcic-forgery-analysis",
    slug: "dcic-forgery-analysis",
    order: 3,
    kind: "竞赛项目",
    title: "DCIC 场景文本图像伪造分析",
    year: "2026",
    status: "公开代码",
    summary:
      "在限时任务中组合视觉语言模型与分割网络，同时完成图像真伪判别、伪造区域定位和归因解释。",
    challenge:
      "单一模型很难同时兼顾高层语义判断与像素级定位，且限时环境要求各模块能够快速独立迭代和稳定交付。",
    role: "方案设计、模型微调与全链路集成",
    contributions: [
      "将视觉语言模型用于全局判别和结构化归因，把分割网络用于像素级掩码定位。",
      "使用 QLoRA 完成参数高效微调，并设计稳健的结构化输出与回退解析。",
      "以解耦级联架构支持双路独立迭代，降低限时开发中的耦合风险。",
    ],
    result:
      "在竞赛窗口内交付完整检测、定位与解释链路，验证“VLM 认知 + 分割定位”路线的工程可行性。",
    methods: [
      "Qwen-VL",
      "QLoRA",
      "ResNet34-UNet",
      "Structured prompting",
      "Segmentation",
    ],
    image: {
      src: "/images/dcic.svg",
      alt: "视觉语言模型判别与分割网络定位组成的图像伪造分析流程图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/DCIC-Discrimination-of-AI-forged-photos",
        kind: "github",
      },
    ],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-rl",
    slug: "kaiwu-reinforcement-learning",
    order: 4,
    kind: "竞赛项目",
    title: "腾讯开悟 · 峡谷追猎强化学习",
    year: "2026",
    status: "全国总决赛三等奖",
    summary:
      "面向局部可观测生存博弈的多目标分层 PPO 方案，联合优化生存、收集与探索策略。",
    challenge:
      "智能体需要在复杂地图中躲避追击并收集资源，任务同时具有局部可观测、多目标冲突、稀疏奖励和长程规划难题。",
    role: "队长、强化学习方案与训练工程",
    contributions: [
      "设计分层 Actor 与多头 Critic，解耦移动、技能和多目标价值估计。",
      "构建多源特征交互与长短期记忆，提升局部观测下的长程决策能力。",
      "使用分阶段奖励和探索反馈缓解稀疏奖励的信用分配问题。",
    ],
    result:
      "方案获得东部赛区初赛前列成绩，并获全国总决赛三等奖；公开仓库记录了网络、奖励与训练设计。",
    methods: [
      "PPO",
      "Actor-Critic",
      "Transformer",
      "Long-term memory",
      "Reward shaping",
    ],
    image: {
      src: "/images/kaiwu.svg",
      alt: "多目标分层 PPO 的状态编码、策略网络与奖励反馈结构图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/KAIWU-RLagent--2026",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    slug: "safecommunity-ai",
    order: 1,
    kind: "Engineering",
    title: "SafeCommunity AI",
    year: "2026",
    status: "Public repository",
    summary:
      "A multi-channel intelligent video analytics system spanning tracking, rule-based alerts, anomaly recognition, and vision-language review.",
    challenge:
      "Rule-only security systems can be brittle, generate false alerts, and provide little explanation. The project needed to connect long-video understanding, open-set events, and readable language feedback.",
    role: "Core algorithms and system engineering",
    contributions: [
      "Combined VideoMAE and CLIP representations with Attention Pooling and Top-K MIL for key-segment aggregation.",
      "Adapted a vision-language model with QLoRA and structured prompts for event review and explanation.",
      "Built a web workflow for multi-stream video, ROI rules, tracking, and alert review.",
    ],
    result:
      "Delivered an end-to-end perception–decision–explanation loop and evaluated it on a public video-anomaly benchmark; the public repository provides implementation evidence.",
    methods: [
      "PyTorch",
      "VideoMAE",
      "CLIP",
      "Qwen-VL",
      "QLoRA",
      "Flask",
      "ByteTrack",
    ],
    image: {
      src: "/images/safecommunity.svg",
      alt: "SafeCommunity AI architecture from video perception to anomaly reasoning and language explanation",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/SafeCommunity-AI",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-multimodal-alignment",
    slug: "medical-multimodal-alignment",
    order: 2,
    kind: "Research",
    title: "Multimodal Clinical Prediction from Brain Imaging",
    year: "2026",
    status: "Research in Progress",
    summary:
      "Aligning frozen 3D MRI representations with regional volumes and clinical text to study lightweight multimodal enhancement.",
    challenge:
      "A pretrained MRI encoder captures imaging patterns but does not directly encode regional atrophy or clinical semantics. Full retraining is costly, while evaluation must guard against shortcut leakage from cognitive variables.",
    role: "Multimodal method design, experiments, and evaluation",
    contributions: [
      "Designed a SigLIP-style contrastive objective across imaging, structured volume, and clinical-text representations.",
      "Used frozen encoders and lightweight projection layers to control compute and preserve transferability.",
      "Developed leakage-aware evaluation and cross-modality ablations with systematic failure analysis.",
    ],
    result:
      "This work is ongoing. To protect unpublished research, this page shares only the problem, high-level method, and evaluation principles—not submission details, internal metrics, or controlled data.",
    methods: [
      "3D MRI",
      "Contrastive learning",
      "BioClinicalBERT",
      "Leakage-aware evaluation",
      "PyTorch",
    ],
    image: {
      src: "/images/medical-alignment.svg",
      alt: "Framework aligning MRI, regional volume, and clinical information in a shared representation space",
    },
    links: [],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "dcic-forgery-analysis",
    slug: "dcic-forgery-analysis",
    order: 3,
    kind: "Competition",
    title: "DCIC Scene-Text Image Forgery Analysis",
    year: "2026",
    status: "Public repository",
    summary:
      "A time-boxed pipeline combining a vision-language model and a segmentation network for forgery detection, localization, and attribution.",
    challenge:
      "A single model struggled to cover both semantic judgment and pixel-level localization, while the competition window demanded fast, independent iteration and reliable integration.",
    role: "System design, model adaptation, and pipeline integration",
    contributions: [
      "Used a vision-language model for global decisions and structured attribution, with a segmentation network for pixel-level masks.",
      "Applied QLoRA for efficient adaptation and designed robust structured output with fallback parsing.",
      "Decoupled the two branches so they could be iterated independently under a strict delivery window.",
    ],
    result:
      "Delivered the full detection, localization, and explanation pipeline within the competition window, validating the engineering value of the VLM-plus-segmentation design.",
    methods: [
      "Qwen-VL",
      "QLoRA",
      "ResNet34-UNet",
      "Structured prompting",
      "Segmentation",
    ],
    image: {
      src: "/images/dcic.svg",
      alt: "Image forgery workflow combining semantic VLM decisions with segmentation-based localization",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/DCIC-Discrimination-of-AI-forged-photos",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-rl",
    slug: "kaiwu-reinforcement-learning",
    order: 4,
    kind: "Competition",
    title: "Tencent Kaiwu · Reinforcement Learning",
    year: "2026",
    status: "National Finals · Third Prize",
    summary:
      "A multi-objective hierarchical PPO agent for a partially observable survival game, balancing survival, collection, and exploration.",
    challenge:
      "The agent must evade pursuit and collect resources in a complex map, bringing partial observability, conflicting objectives, sparse rewards, and long-horizon planning into one task.",
    role: "Team lead, reinforcement-learning design, and training engineering",
    contributions: [
      "Designed hierarchical actors and multi-head critics to separate movement, skills, and objective-specific value estimates.",
      "Built multi-source feature interaction and long/short-term memory for decisions under partial observation.",
      "Used staged reward shaping and exploration feedback to improve credit assignment under sparse rewards.",
    ],
    result:
      "The solution placed near the top of the regional qualifier and received a national finals third prize; the public repository documents the network, rewards, and training design.",
    methods: [
      "PPO",
      "Actor-Critic",
      "Transformer",
      "Long-term memory",
      "Reward shaping",
    ],
    image: {
      src: "/images/kaiwu.svg",
      alt: "Hierarchical multi-objective PPO architecture with state encoding, policies, critics, and reward feedback",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/KAIWU-RLagent--2026",
        kind: "github",
      },
    ],
  },
];

export const experiences: ExperienceEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-research",
    order: 1,
    period: "2026.03 — 至今",
    organization: "医学影像多模态研究合作",
    role: "研究成员",
    summary:
      "围绕冻结 3D MRI 编码器的轻量多模态增强，负责方法设计、实验协议和系统性评测。",
    highlights: [
      "对齐脑影像、区域体积与临床文本表征。",
      "建立防止标签泄漏的评测协议与跨模态消融。",
      "维护可复现实验配置、日志和结果核验流程。",
    ],
    methods: ["3D MRI", "Contrastive learning", "BioClinicalBERT", "PyTorch"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "video-rd",
    order: 2,
    period: "2026.01 — 2026.05",
    organization: "智能视频分析产学合作研发",
    role: "研发工程师",
    summary:
      "针对安防误报和语义解释不足，参与异常识别、开放集复核与 Web 告警闭环的完整研发。",
    highlights: [
      "实现长时序视频特征与弱监督异常聚合。",
      "以参数高效微调适配视觉语言模型的场景解释能力。",
      "集成多路视频、ROI 规则、跟踪与告警交互。",
    ],
    methods: ["VideoMAE", "CLIP", "Qwen-VL", "QLoRA", "Flask"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "education",
    order: 3,
    period: "2024.09 — 2028.06",
    organization: "宁波大学",
    role: "数学与应用数学 · 理学学士",
    summary:
      "以数学训练为基础，持续学习机器学习、深度学习、计算机视觉和数学建模。",
    highlights: [
      "课程包括 Python 程序设计、机器学习、深度学习与数学建模。",
      "通过科研、竞赛和工程项目建立从问题建模到系统交付的实践链路。",
    ],
    methods: ["Mathematics", "Machine learning", "Deep learning", "Modeling"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-research",
    order: 1,
    period: "Mar 2026 — Present",
    organization: "Multimodal Medical Imaging Research Collaboration",
    role: "Research contributor",
    summary:
      "Working on lightweight multimodal enhancement for frozen 3D MRI encoders, with responsibility for methods, protocols, and systematic evaluation.",
    highlights: [
      "Aligned imaging, regional-volume, and clinical-text representations.",
      "Built leakage-aware protocols and cross-modality ablations.",
      "Maintained reproducible experiment configurations, logs, and result checks.",
    ],
    methods: ["3D MRI", "Contrastive learning", "BioClinicalBERT", "PyTorch"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "video-rd",
    order: 2,
    period: "Jan 2026 — May 2026",
    organization: "Industry-Academic Video Analytics R&D",
    role: "R&D Engineer",
    summary:
      "Developed anomaly recognition, open-set review, and a web-based alert loop for security-video scenarios with high false-positive and explanation costs.",
    highlights: [
      "Implemented long-video features and weakly supervised anomaly aggregation.",
      "Adapted a vision-language model for domain explanations with parameter-efficient tuning.",
      "Integrated multi-stream video, ROI rules, tracking, and alert review.",
    ],
    methods: ["VideoMAE", "CLIP", "Qwen-VL", "QLoRA", "Flask"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "education",
    order: 3,
    period: "Sep 2024 — Jun 2028",
    organization: "Ningbo University",
    role: "B.Sc. in Mathematics and Applied Mathematics",
    summary:
      "Building a mathematical foundation alongside sustained work in machine learning, computer vision, and mathematical modeling.",
    highlights: [
      "Coursework includes Python programming, machine learning, deep learning, and mathematical modeling.",
      "Research, competitions, and engineering projects connect formal modeling to working systems.",
    ],
    methods: ["Mathematics", "Machine learning", "Deep learning", "Modeling"],
  },
];

export const achievements: AchievementEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-prize",
    order: 1,
    date: "2026",
    title: "腾讯开悟强化学习竞赛 · 全国总决赛三等奖",
    scope: "国家级",
    note: "负责多目标分层 PPO、奖励设计与训练迭代。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "ascend-prize",
    order: 2,
    date: "本科阶段",
    title: "华为昇腾 AI 创新大赛 · 浙江赛区银奖",
    scope: "省级",
    note: "围绕 AI 模型与工程系统完成方案开发和展示。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mcm-awards",
    order: 3,
    date: "本科阶段",
    title: "美国大学生数学建模竞赛 · M / H 奖",
    scope: "国际竞赛",
    note: "完成问题建模、数值分析与论文表达。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "scholarship",
    order: 4,
    date: "本科阶段",
    title: "宁波大学本科二等奖学金",
    scope: "校级",
    note: "综合课程学习与实践表现。",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-prize",
    order: 1,
    date: "2026",
    title: "Tencent Kaiwu Reinforcement Learning · National Finals Third Prize",
    scope: "National",
    note: "Led hierarchical multi-objective PPO, reward design, and training iteration.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "ascend-prize",
    order: 2,
    date: "Undergraduate",
    title: "Huawei Ascend AI Innovation Competition · Zhejiang Silver Award",
    scope: "Provincial",
    note: "Developed and presented an AI model and engineering system.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mcm-awards",
    order: 3,
    date: "Undergraduate",
    title: "MCM/ICM · Meritorious / Honorable Mention",
    scope: "International",
    note: "Contributed problem formulation, numerical analysis, and technical writing.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "scholarship",
    order: 4,
    date: "Undergraduate",
    title: "Ningbo University Second-Class Undergraduate Scholarship",
    scope: "University",
    note: "Awarded for academic and practical performance.",
  },
];

export const interests: InterestEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "training",
    order: 1,
    marker: "01",
    title: "健身与户外运动",
    description: "通过规律力量训练和户外活动保持长期节奏，也享受持续进步带来的确定感。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "hiking",
    order: 2,
    marker: "02",
    title: "徒步与骑行",
    description: "喜欢用一段长路线认识城市和自然，在体力分配与路线判断中训练耐心。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mystery",
    order: 3,
    marker: "03",
    title: "协作式推理",
    description: "喜欢剧本推理与叙事解谜，在有限信息中建立假设、沟通线索并共同完成判断。",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "training",
    order: 1,
    marker: "01",
    title: "Strength & Outdoor Training",
    description:
      "Regular strength work and outdoor activity help me sustain a long-term rhythm and appreciate measurable progress.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "hiking",
    order: 2,
    marker: "02",
    title: "Hiking & Cycling",
    description:
      "Long routes are a way to understand cities and landscapes while practicing pacing, judgment, and patience.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mystery",
    order: 3,
    marker: "03",
    title: "Collaborative Mystery Solving",
    description:
      "I enjoy narrative deduction: building hypotheses from limited evidence, exchanging clues, and converging on a shared judgment.",
  },
];

export const skillGroups: SkillGroup[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "research-methods",
    order: 1,
    title: "研究方法",
    items: ["视频建模", "多模态对齐", "对比学习", "弱监督学习", "消融与可靠评测"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "tooling",
    order: 2,
    title: "模型与工具",
    items: ["PyTorch", "Transformers", "LoRA / QLoRA", "CLIP", "VideoMAE"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "engineering",
    order: 3,
    title: "工程能力",
    items: ["训练与评测管线", "数据处理", "Flask / Web", "视频流系统", "Git"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "research-methods",
    order: 1,
    title: "Research Methods",
    items: [
      "Video modeling",
      "Multimodal alignment",
      "Contrastive learning",
      "Weak supervision",
      "Ablation & evaluation",
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "tooling",
    order: 2,
    title: "Models & Tools",
    items: ["PyTorch", "Transformers", "LoRA / QLoRA", "CLIP", "VideoMAE"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "engineering",
    order: 3,
    title: "Engineering",
    items: [
      "Training & evaluation pipelines",
      "Data processing",
      "Flask / Web",
      "Video systems",
      "Git",
    ],
  },
];
