import type {
  AchievementEntry,
  ExperienceEntry,
  InterestEntry,
  SkillGroup,
  SkillLogo,
  SiteProfile,
  WorkEntry,
} from "./types";

const updatedAt = "2026-07-26";

export const siteProfiles: SiteProfile[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    name: "齐梓桐",
    alternateName: "Zitong Qi",
    field: "计算机视觉 · 多模态学习 · 具身 VLN",
    eyebrow: "宁波大学 · 数学与应用数学本科生",
    introduction:
      "宁波大学数学与应用数学本科生。主要关注真实场景中的视频理解、多模态表征，以及视觉语言导航与具身模型轻量化。我目前在宁波东方理工大学 EIT 的 EAST Lab 做 VLN 相关研究，平时会整理代码、配置和实验记录，确保结果能够复跑。",
    availability: "开放计算机视觉、多模态与具身智能方向的科研交流和实习机会。",
    current: "宁波大学 · 数学与应用数学",
    location: "中国 · 宁波",
    github: "https://github.com/fingercd",
    focus: ["计算机视觉", "多模态学习", "视觉语言导航与具身智能"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    name: "Zitong Qi",
    alternateName: "齐梓桐",
    field: "Computer Vision · Multimodal Learning · Embodied VLN",
    eyebrow: "Mathematics undergraduate at Ningbo University",
    introduction:
      "I am an undergraduate in Mathematics and Applied Mathematics at Ningbo University. My current work covers video understanding in real-world systems, multimodal representation learning, and lightweight vision-language navigation at EAST Lab, Eastern Institute of Technology, Ningbo.",
    availability:
      "Open to research conversations and internships in computer vision, multimodal learning, and embodied AI.",
    current: "Ningbo University · Mathematics",
    location: "Ningbo, China",
    github: "https://github.com/fingercd",
    focus: [
      "Computer vision",
      "Multimodal learning",
      "Vision-language navigation & embodied AI",
    ],
  },
];

export const projects: WorkEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    slug: "safecommunity-ai",
    order: 1,
    kind: "工程项目",
    title: "SafeCommunity AI",
    year: "2026.01 至 2026.03",
    status: "公开代码",
    homepageContribution:
      "负责核心算法与系统集成，将目标检测与跟踪、ROI 规则、视频异常识别和视觉语言模型复核接入同一套 Web 工作流。",
    summary:
      "面向复杂监控场景的多路智能视频分析系统，覆盖目标跟踪、规则告警、异常识别与视觉语言模型复核。",
    challenge:
      "传统安防系统依赖固定规则，容易误报，也难以说明事件为什么异常。项目需要同时处理长时序视频、开放集事件和可读的语言解释。",
    role: "核心算法与系统工程",
    contributions: [
      "组合 VideoMAE 与 CLIP 表征，并使用 Attention Pooling 和 Top-K MIL 聚合关键片段。",
      "以 QLoRA 适配视觉语言模型，配合结构化提示完成事件复核与解释。",
      "构建多路视频、ROI 规则、跟踪与告警闭环的 Web 展示系统。",
    ],
    result:
      "项目完成多路视频接入、告警复核与结果展示。公开仓库包含系统架构和实现。",
    methods: [
      "PyTorch",
      "VideoMAE",
      "CLIP",
      "Qwen-VL",
      "QLoRA",
      "Flask",
      "ByteTrack",
    ],
    image: {
      src: "/images/safecommunity-monitor.png",
      alt: "SafeCommunity AI 多模态智能视频监控系统的项目总览图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/SafeCommunity-AI",
        kind: "github",
      },
    ],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-multimodal-alignment",
    slug: "medical-multimodal-alignment",
    order: 2,
    kind: "论文",
    title:
      "Anatomical-Clinical Vision Fusion for Multimodal Clinical Prediction with Frozen Brain MRI Encoders",
    year: "2026",
    status: "在投",
    venue: "IEEE BIBM 2026",
    homepageContribution: "多模态方法设计、实验与评测",
    summary:
      "围绕冻结的 3D 脑 MRI 编码器，对齐 MRI 表征、AAL 脑区体积和临床信息，研究轻量多模态增强与防泄漏评测。",
    challenge:
      "预训练 MRI 编码器能够提取影像表征，却不直接包含脑区体积和临床语义。直接重训成本高，评测中还需避免认知评分等信息造成标签泄漏。",
    role: "多模态方法设计、实验与评测",
    contributions: [
      "设计 SigLIP 风格跨模态对比目标，将影像、结构化体积与临床文本映射到共享空间。",
      "采用冻结编码器与轻量投影层，控制训练成本并保留可迁移性。",
      "设计排除认知捷径的评测协议，并开展跨模态消融与失败分析。",
    ],
    result: "论文目前在投。公开页面不展示内部指标或受控数据。",
    methods: [
      "3D MRI",
      "Contrastive learning",
      "BioClinicalBERT",
      "Leakage-aware evaluation",
      "PyTorch",
    ],
    image: {
      src: "/images/acvf-pipeline.png",
      alt: "ACVF 将脑 MRI、AAL 脑区体积和临床信息融合用于临床预测的论文流程图",
    },
    links: [],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: false,
    updatedAt,
    key: "dcic-forgery-analysis",
    slug: "dcic-forgery-analysis",
    order: 3,
    kind: "竞赛项目",
    title: "DCIC 场景文本图像伪造分析",
    year: "2026",
    status: "公开代码",
    summary:
      "在限时任务中组合视觉语言模型与分割网络，同时完成图像真伪判别、伪造区域定位和归因解释。",
    challenge:
      "单一模型很难同时兼顾高层语义判断与像素级定位，且限时环境要求各模块能够快速独立迭代和稳定交付。",
    role: "方案设计、模型微调与全链路集成",
    contributions: [
      "将视觉语言模型用于全局判别和结构化归因，把分割网络用于像素级掩码定位。",
      "使用 QLoRA 完成参数高效微调，并设计稳健的结构化输出与回退解析。",
      "以解耦级联架构支持双路独立迭代，降低限时开发中的耦合风险。",
    ],
    result:
      "在竞赛窗口内交付完整检测、定位与解释链路，验证“VLM 认知 + 分割定位”路线的工程可行性。",
    methods: [
      "Qwen-VL",
      "QLoRA",
      "ResNet34-UNet",
      "Structured prompting",
      "Segmentation",
    ],
    image: {
      src: "/images/dcic.svg",
      alt: "视觉语言模型判别与分割网络定位组成的图像伪造分析流程图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/DCIC-Discrimination-of-AI-forged-photos",
        kind: "github",
      },
    ],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: false,
    updatedAt,
    key: "kaiwu-rl",
    slug: "kaiwu-reinforcement-learning",
    order: 4,
    kind: "竞赛项目",
    title: "腾讯开悟 · 峡谷追猎强化学习",
    year: "2026",
    status: "全国总决赛三等奖",
    summary:
      "面向局部可观测生存博弈的多目标分层 PPO 方案，联合优化生存、收集与探索策略。",
    challenge:
      "智能体需要在复杂地图中躲避追击并收集资源，任务同时具有局部可观测、多目标冲突、稀疏奖励和长程规划难题。",
    role: "队长、强化学习方案与训练工程",
    contributions: [
      "设计分层 Actor 与多头 Critic，将移动、技能释放和不同任务目标的价值估计解耦。",
      "融合局部观测、目标关系和历史状态，并使用 LSTM / Transformer Policy 维持长短期决策上下文。",
      "围绕生存、资源收集与地图探索设计多目标奖励和阶段化 Reward Shaping，缓解稀疏奖励与目标冲突。",
      "持续迭代采样、评估与训练配置，结合失败回放定位策略坍缩和探索不足问题。",
    ],
    result:
      "方案获得东部赛区初赛前列成绩，并获全国总决赛三等奖；公开仓库记录了网络、奖励与训练设计。",
    methods: [
      "PPO",
      "Actor-Critic",
      "Hierarchical policy",
      "LSTM / Transformer Policy",
      "Multi-objective rewards",
      "Reward shaping",
    ],
    image: {
      src: "/images/kaiwu.svg",
      alt: "多目标分层 PPO 的状态编码、策略网络与奖励反馈结构图",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/KAIWU-RLagent--2026",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    slug: "safecommunity-ai",
    order: 1,
    kind: "Engineering",
    title: "SafeCommunity AI",
    year: "Jan 2026 to Mar 2026",
    status: "Public repository",
    homepageContribution:
      "Led the core algorithms and system integration, connecting detection and tracking, ROI rules, video anomaly recognition, and vision-language review in one web workflow.",
    summary:
      "A multi-channel intelligent video analytics system spanning tracking, rule-based alerts, anomaly recognition, and vision-language review.",
    challenge:
      "Rule-only security systems can be brittle, generate false alerts, and provide little explanation. The project needed to connect long-video understanding, open-set events, and readable language feedback.",
    role: "Core algorithms and system engineering",
    contributions: [
      "Combined VideoMAE and CLIP representations with Attention Pooling and Top-K MIL for key-segment aggregation.",
      "Adapted a vision-language model with QLoRA and structured prompts for event review and explanation.",
      "Built a web workflow for multi-stream video, ROI rules, tracking, and alert review.",
    ],
    result:
      "The system connects multi-stream inputs with alert review and result display. The public repository includes the architecture and implementation.",
    methods: [
      "PyTorch",
      "VideoMAE",
      "CLIP",
      "Qwen-VL",
      "QLoRA",
      "Flask",
      "ByteTrack",
    ],
    image: {
      src: "/images/safecommunity-monitor.png",
      alt: "SafeCommunity AI project overview for a multimodal intelligent video-monitoring system",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/SafeCommunity-AI",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "medical-multimodal-alignment",
    slug: "medical-multimodal-alignment",
    order: 2,
    kind: "Paper",
    title:
      "Anatomical-Clinical Vision Fusion for Multimodal Clinical Prediction with Frozen Brain MRI Encoders",
    year: "2026",
    status: "Under Review",
    venue: "IEEE BIBM 2026",
    homepageContribution: "Multimodal method design, experiments, and evaluation",
    summary:
      "Aligning frozen 3D brain MRI representations with AAL regional volumes and clinical information for lightweight multimodal enhancement and leakage-aware evaluation.",
    challenge:
      "A pretrained MRI encoder captures imaging patterns but does not directly encode regional atrophy or clinical semantics. Full retraining is costly, while evaluation must guard against shortcut leakage from cognitive variables.",
    role: "Multimodal method design, experiments, and evaluation",
    contributions: [
      "Designed a SigLIP-style contrastive objective across imaging, structured volume, and clinical-text representations.",
      "Used frozen encoders and lightweight projection layers to control compute and preserve transferability.",
      "Developed leakage-aware evaluation and cross-modality ablations with systematic failure analysis.",
    ],
    result:
      "The paper is under review at IEEE BIBM 2026. This public page omits internal metrics and controlled data.",
    methods: [
      "3D MRI",
      "Contrastive learning",
      "BioClinicalBERT",
      "Leakage-aware evaluation",
      "PyTorch",
    ],
    image: {
      src: "/images/acvf-pipeline.png",
      alt: "ACVF pipeline fusing brain MRI, AAL regional volumes, and clinical information for clinical prediction",
    },
    links: [],
  },
  {
    locale: "en",
    visibility: "public",
    featured: false,
    updatedAt,
    key: "dcic-forgery-analysis",
    slug: "dcic-forgery-analysis",
    order: 3,
    kind: "Competition",
    title: "DCIC Scene-Text Image Forgery Analysis",
    year: "2026",
    status: "Public repository",
    summary:
      "A time-boxed pipeline combining a vision-language model and a segmentation network for forgery detection, localization, and attribution.",
    challenge:
      "A single model struggled to cover both semantic judgment and pixel-level localization, while the competition window demanded fast, independent iteration and reliable integration.",
    role: "System design, model adaptation, and pipeline integration",
    contributions: [
      "Used a vision-language model for global decisions and structured attribution, with a segmentation network for pixel-level masks.",
      "Applied QLoRA for efficient adaptation and designed robust structured output with fallback parsing.",
      "Decoupled the two branches so they could be iterated independently under a strict delivery window.",
    ],
    result:
      "Delivered the full detection, localization, and explanation pipeline within the competition window, validating the engineering value of the VLM-plus-segmentation design.",
    methods: [
      "Qwen-VL",
      "QLoRA",
      "ResNet34-UNet",
      "Structured prompting",
      "Segmentation",
    ],
    image: {
      src: "/images/dcic.svg",
      alt: "Image forgery workflow combining semantic VLM decisions with segmentation-based localization",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/DCIC-Discrimination-of-AI-forged-photos",
        kind: "github",
      },
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: false,
    updatedAt,
    key: "kaiwu-rl",
    slug: "kaiwu-reinforcement-learning",
    order: 4,
    kind: "Competition",
    title: "Tencent Kaiwu · Reinforcement Learning",
    year: "2026",
    status: "National Finals · Third Prize",
    summary:
      "A multi-objective hierarchical PPO agent for a partially observable survival game, balancing survival, collection, and exploration.",
    challenge:
      "The agent must evade pursuit and collect resources in a complex map, bringing partial observability, conflicting objectives, sparse rewards, and long-horizon planning into one task.",
    role: "Team lead, reinforcement-learning design, and training engineering",
    contributions: [
      "Designed hierarchical actors and multi-head critics to separate movement, skill use, and objective-specific value estimates.",
      "Fused local observations, target relations, and state history with an LSTM / Transformer policy for short- and long-horizon context.",
      "Designed multi-objective rewards for survival, resource collection, and exploration, with staged reward shaping for sparse feedback and conflicting goals.",
      "Iterated sampling, evaluation, and training configurations, using failure replays to diagnose policy collapse and insufficient exploration.",
    ],
    result:
      "The solution placed near the top of the regional qualifier and received a national finals third prize; the public repository documents the network, rewards, and training design.",
    methods: [
      "PPO",
      "Actor-Critic",
      "Hierarchical policy",
      "LSTM / Transformer Policy",
      "Multi-objective rewards",
      "Reward shaping",
    ],
    image: {
      src: "/images/kaiwu.svg",
      alt: "Hierarchical multi-objective PPO architecture with state encoding, policies, critics, and reward feedback",
    },
    links: [
      {
        label: "GitHub",
        href: "https://github.com/fingercd/KAIWU-RLagent--2026",
        kind: "github",
      },
    ],
  },
];

export const experiences: ExperienceEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "education",
    order: 1,
    period: "2024.09 至 2028.06",
    organization: "宁波大学",
    role: "数学与应用数学本科",
    summary: "以数学训练为基础，持续学习并实践机器学习、计算机视觉与多模态方法。",
    highlights: [],
    methods: [],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    order: 2,
    period: "2026.01 至 2026.03",
    organization: "甬江实验室（乐橙实习）",
    group: "SafeCommunity AI",
    role: "核心算法与系统工程",
    summary:
      "完成多路视频接入、目标检测与跟踪、规则告警、视频异常识别和 VLM 复核的系统集成。",
    highlights: [],
    methods: [],
    logo: {
      src: "/images/organizations/yongjiang-lab.svg",
      alt: "甬江实验室标志",
    },
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "east-lab-vln",
    order: 3,
    period: "2026.06 至今",
    organization: "宁波东方理工大学 EIT",
    group: "EAST Lab · 张伟课题组",
    role: "研究助理",
    summary:
      "围绕视觉语言导航（VLN）评测复现、模型行为分析与具身智能模型轻量化方案验证开展研究。",
    highlights: [],
    methods: [],
    logo: {
      src: "/images/organizations/eit-logo.png",
      alt: "宁波东方理工大学 EIT 校徽与中英文校名",
    },
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "education",
    order: 1,
    period: "Sep 2024 to Jun 2028",
    organization: "Ningbo University",
    role: "B.Sc. in Mathematics and Applied Mathematics",
    summary:
      "Building a mathematical foundation while working on machine learning, computer vision, and multimodal methods.",
    highlights: [],
    methods: [],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "safecommunity-ai",
    order: 2,
    period: "Jan 2026 to Mar 2026",
    organization: "Yongjiang Laboratory (Lecheng Internship)",
    group: "SafeCommunity AI",
    role: "Core algorithms and system engineering",
    summary:
      "Integrated multi-stream video, detection and tracking, rule-based alerts, video anomaly recognition, and VLM review into one system.",
    highlights: [],
    methods: [],
    logo: {
      src: "/images/organizations/yongjiang-lab.svg",
      alt: "Yongjiang Laboratory logo",
    },
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "east-lab-vln",
    order: 3,
    period: "Jun 2026 to present",
    organization: "Eastern Institute of Technology, Ningbo (EIT)",
    group: "EAST Lab · Wei Zhang Group",
    role: "Research Assistant",
    summary:
      "Working on vision-language navigation (VLN), including evaluation reproduction, model-behavior analysis, and lightweight embodied-model experiments.",
    highlights: [],
    methods: [],
    logo: {
      src: "/images/organizations/eit-logo.png",
      alt: "Eastern Institute of Technology, Ningbo (EIT) logo and wordmark",
    },
  },
];

export const skills: SkillGroup[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "programming",
    order: 1,
    title: "编程与脚本",
    items: ["Python", "TypeScript / JavaScript", "HTML / CSS", "Bash / PowerShell"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "deep-learning",
    order: 2,
    title: "深度学习与多模态",
    items: ["PyTorch", "Transformers", "PEFT / QLoRA", "CLIP", "Qwen-VL"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "computer-vision",
    order: 3,
    title: "计算机视觉",
    items: ["OpenCV", "YOLOv8", "VideoMAE v2", "SAM 2", "ByteTrack"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "embodied-ai",
    order: 4,
    title: "具身智能与仿真",
    items: ["Habitat-Lab", "Habitat-Sim", "VLN-CE", "Isaac Lab", "Isaac Sim"],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "reinforcement-learning",
    order: 5,
    title: "强化学习与决策",
    items: [
      "PPO / Actor-Critic",
      "分层策略",
      "多目标奖励",
      "LSTM / Transformer Policy",
      "Reward Shaping",
    ],
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "data-modeling",
    order: 6,
    title: "数据分析与建模",
    items: ["NumPy", "Pandas", "SciPy", "scikit-learn", "XGBoost"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "programming",
    order: 1,
    title: "Programming & Scripting",
    items: ["Python", "TypeScript / JavaScript", "HTML / CSS", "Bash / PowerShell"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "deep-learning",
    order: 2,
    title: "Deep Learning & Multimodal AI",
    items: ["PyTorch", "Transformers", "PEFT / QLoRA", "CLIP", "Qwen-VL"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "computer-vision",
    order: 3,
    title: "Computer Vision",
    items: ["OpenCV", "YOLOv8", "VideoMAE v2", "SAM 2", "ByteTrack"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "embodied-ai",
    order: 4,
    title: "Embodied AI & Simulation",
    items: ["Habitat-Lab", "Habitat-Sim", "VLN-CE", "Isaac Lab", "Isaac Sim"],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "reinforcement-learning",
    order: 5,
    title: "Reinforcement Learning & Decision Making",
    items: [
      "PPO / Actor-Critic",
      "Hierarchical policies",
      "Multi-objective rewards",
      "LSTM / Transformer Policy",
      "Reward Shaping",
    ],
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "data-modeling",
    order: 6,
    title: "Data Analysis & Modeling",
    items: ["NumPy", "Pandas", "SciPy", "scikit-learn", "XGBoost"],
  },
];

export const skillLogos: SkillLogo[] = [
  { key: "python", label: "Python", src: "/images/skills/python.svg" },
  { key: "pytorch", label: "PyTorch", src: "/images/skills/pytorch.svg" },
  {
    key: "hugging-face",
    label: "Hugging Face",
    src: "/images/skills/huggingface.svg",
  },
  { key: "opencv", label: "OpenCV", src: "/images/skills/opencv.svg" },
  { key: "nvidia", label: "NVIDIA / Isaac", src: "/images/skills/nvidia.svg" },
  { key: "numpy", label: "NumPy", src: "/images/skills/numpy.svg" },
];

export const achievements: AchievementEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-prize",
    order: 1,
    date: "2026",
    title: "腾讯开悟强化学习竞赛 · 全国总决赛三等奖",
    scope: "国家级",
    note: "负责分层 PPO、奖励设计与训练迭代。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "ascend-prize",
    order: 2,
    date: "本科阶段",
    title: "华为昇腾 AI 创新大赛 · 浙江赛区银奖",
    scope: "省级",
    note: "参与方案开发与工程展示。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mcm-awards",
    order: 3,
    date: "本科阶段",
    title: "美国大学生数学建模竞赛 · M / H 奖",
    scope: "国际竞赛",
    note: "负责问题建模、数值分析与论文写作。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "scholarship",
    order: 4,
    date: "本科阶段",
    title: "宁波大学本科二等奖学金",
    scope: "校级",
    note: "基于课程学习与综合表现评定。",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "kaiwu-prize",
    order: 1,
    date: "2026",
    title: "Tencent Kaiwu Reinforcement Learning · National Finals Third Prize",
    scope: "National",
    note: "Led hierarchical PPO, reward design, and training iteration.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "ascend-prize",
    order: 2,
    date: "Undergraduate",
    title: "Huawei Ascend AI Innovation Competition · Zhejiang Silver Award",
    scope: "Provincial",
    note: "Contributed to solution development and the engineering presentation.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mcm-awards",
    order: 3,
    date: "Undergraduate",
    title: "MCM/ICM · Meritorious / Honorable Mention",
    scope: "International",
    note: "Worked on problem formulation, numerical analysis, and technical writing.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "scholarship",
    order: 4,
    date: "Undergraduate",
    title: "Ningbo University Second-Class Undergraduate Scholarship",
    scope: "University",
    note: "Awarded for coursework and overall performance.",
  },
];

export const interests: InterestEntry[] = [
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "training",
    order: 1,
    title: "力量训练与户外运动",
    description: "用规律训练保持长期节奏。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "hiking",
    order: 2,
    title: "徒步与骑行",
    description: "喜欢通过长路线认识城市与自然。",
  },
  {
    locale: "zh",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mystery",
    order: 3,
    title: "剧本推理与协作解谜",
    description: "享受从有限信息中建立假设并共同判断。",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "training",
    order: 1,
    title: "Strength Training & Outdoor Activity",
    description: "Regular training helps me keep a steady long-term rhythm.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "hiking",
    order: 2,
    title: "Hiking & Cycling",
    description: "I enjoy getting to know cities and landscapes through long routes.",
  },
  {
    locale: "en",
    visibility: "public",
    featured: true,
    updatedAt,
    key: "mystery",
    order: 3,
    title: "Narrative Deduction & Collaborative Puzzles",
    description: "I enjoy building hypotheses from limited evidence and reasoning together.",
  },
];
